/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRatingRouteImport } from './routes/_authenticated/rating'
import { Route as AuthenticatedIncomesRouteImport } from './routes/_authenticated/incomes'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDebtsRouteImport } from './routes/_authenticated/debts'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicBotTaskRouteImport } from './routes/api/public/bot/task'
import { Route as ApiPublicBotStatusQueryRouteImport } from './routes/api/public/bot/status-query'
import { Route as ApiPublicBotRescheduleTaskRouteImport } from './routes/api/public/bot/reschedule-task'
import { Route as ApiPublicBotParseRouteImport } from './routes/api/public/bot/parse'
import { Route as ApiPublicBotIncomeRouteImport } from './routes/api/public/bot/income'
import { Route as ApiPublicBotGoalContributionRouteImport } from './routes/api/public/bot/goal-contribution'
import { Route as ApiPublicBotExpenseRouteImport } from './routes/api/public/bot/expense'
import { Route as ApiPublicBotDebtPaymentRouteImport } from './routes/api/public/bot/debt-payment'
import { Route as ApiPublicBotCreateGoalRouteImport } from './routes/api/public/bot/create-goal'
import { Route as ApiPublicBotCreateDebtRouteImport } from './routes/api/public/bot/create-debt'
import { Route as ApiPublicBotCloseTaskRouteImport } from './routes/api/public/bot/close-task'
import { Route as ApiPublicBotCronWeeklyReportRouteImport } from './routes/api/public/bot/cron/weekly-report'
import { Route as ApiPublicBotCronPaymentRemindersRouteImport } from './routes/api/public/bot/cron/payment-reminders'
import { Route as ApiPublicBotCronAnomalyAlertsRouteImport } from './routes/api/public/bot/cron/anomaly-alerts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRatingRoute = AuthenticatedRatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomesRoute = AuthenticatedIncomesRouteImport.update({
  id: '/incomes',
  path: '/incomes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDebtsRoute = AuthenticatedDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicBotTaskRoute = ApiPublicBotTaskRouteImport.update({
  id: '/api/public/bot/task',
  path: '/api/public/bot/task',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotStatusQueryRoute = ApiPublicBotStatusQueryRouteImport.update({
  id: '/api/public/bot/status-query',
  path: '/api/public/bot/status-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotRescheduleTaskRoute =
  ApiPublicBotRescheduleTaskRouteImport.update({
    id: '/api/public/bot/reschedule-task',
    path: '/api/public/bot/reschedule-task',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBotParseRoute = ApiPublicBotParseRouteImport.update({
  id: '/api/public/bot/parse',
  path: '/api/public/bot/parse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotIncomeRoute = ApiPublicBotIncomeRouteImport.update({
  id: '/api/public/bot/income',
  path: '/api/public/bot/income',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotGoalContributionRoute =
  ApiPublicBotGoalContributionRouteImport.update({
    id: '/api/public/bot/goal-contribution',
    path: '/api/public/bot/goal-contribution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBotExpenseRoute = ApiPublicBotExpenseRouteImport.update({
  id: '/api/public/bot/expense',
  path: '/api/public/bot/expense',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotDebtPaymentRoute = ApiPublicBotDebtPaymentRouteImport.update({
  id: '/api/public/bot/debt-payment',
  path: '/api/public/bot/debt-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotCreateGoalRoute = ApiPublicBotCreateGoalRouteImport.update({
  id: '/api/public/bot/create-goal',
  path: '/api/public/bot/create-goal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotCreateDebtRoute = ApiPublicBotCreateDebtRouteImport.update({
  id: '/api/public/bot/create-debt',
  path: '/api/public/bot/create-debt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotCloseTaskRoute = ApiPublicBotCloseTaskRouteImport.update({
  id: '/api/public/bot/close-task',
  path: '/api/public/bot/close-task',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotCronWeeklyReportRoute =
  ApiPublicBotCronWeeklyReportRouteImport.update({
    id: '/api/public/bot/cron/weekly-report',
    path: '/api/public/bot/cron/weekly-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBotCronPaymentRemindersRoute =
  ApiPublicBotCronPaymentRemindersRouteImport.update({
    id: '/api/public/bot/cron/payment-reminders',
    path: '/api/public/bot/cron/payment-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBotCronAnomalyAlertsRoute =
  ApiPublicBotCronAnomalyAlertsRouteImport.update({
    id: '/api/public/bot/cron/anomaly-alerts',
    path: '/api/public/bot/cron/anomaly-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/debts': typeof AuthenticatedDebtsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/incomes': typeof AuthenticatedIncomesRoute
  '/rating': typeof AuthenticatedRatingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/public/bot/close-task': typeof ApiPublicBotCloseTaskRoute
  '/api/public/bot/create-debt': typeof ApiPublicBotCreateDebtRoute
  '/api/public/bot/create-goal': typeof ApiPublicBotCreateGoalRoute
  '/api/public/bot/debt-payment': typeof ApiPublicBotDebtPaymentRoute
  '/api/public/bot/expense': typeof ApiPublicBotExpenseRoute
  '/api/public/bot/goal-contribution': typeof ApiPublicBotGoalContributionRoute
  '/api/public/bot/income': typeof ApiPublicBotIncomeRoute
  '/api/public/bot/parse': typeof ApiPublicBotParseRoute
  '/api/public/bot/reschedule-task': typeof ApiPublicBotRescheduleTaskRoute
  '/api/public/bot/status-query': typeof ApiPublicBotStatusQueryRoute
  '/api/public/bot/task': typeof ApiPublicBotTaskRoute
  '/api/public/bot/cron/anomaly-alerts': typeof ApiPublicBotCronAnomalyAlertsRoute
  '/api/public/bot/cron/payment-reminders': typeof ApiPublicBotCronPaymentRemindersRoute
  '/api/public/bot/cron/weekly-report': typeof ApiPublicBotCronWeeklyReportRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/debts': typeof AuthenticatedDebtsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/incomes': typeof AuthenticatedIncomesRoute
  '/rating': typeof AuthenticatedRatingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/bot/close-task': typeof ApiPublicBotCloseTaskRoute
  '/api/public/bot/create-debt': typeof ApiPublicBotCreateDebtRoute
  '/api/public/bot/create-goal': typeof ApiPublicBotCreateGoalRoute
  '/api/public/bot/debt-payment': typeof ApiPublicBotDebtPaymentRoute
  '/api/public/bot/expense': typeof ApiPublicBotExpenseRoute
  '/api/public/bot/goal-contribution': typeof ApiPublicBotGoalContributionRoute
  '/api/public/bot/income': typeof ApiPublicBotIncomeRoute
  '/api/public/bot/parse': typeof ApiPublicBotParseRoute
  '/api/public/bot/reschedule-task': typeof ApiPublicBotRescheduleTaskRoute
  '/api/public/bot/status-query': typeof ApiPublicBotStatusQueryRoute
  '/api/public/bot/task': typeof ApiPublicBotTaskRoute
  '/api/public/bot/cron/anomaly-alerts': typeof ApiPublicBotCronAnomalyAlertsRoute
  '/api/public/bot/cron/payment-reminders': typeof ApiPublicBotCronPaymentRemindersRoute
  '/api/public/bot/cron/weekly-report': typeof ApiPublicBotCronWeeklyReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/debts': typeof AuthenticatedDebtsRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/incomes': typeof AuthenticatedIncomesRoute
  '/_authenticated/rating': typeof AuthenticatedRatingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/bot/close-task': typeof ApiPublicBotCloseTaskRoute
  '/api/public/bot/create-debt': typeof ApiPublicBotCreateDebtRoute
  '/api/public/bot/create-goal': typeof ApiPublicBotCreateGoalRoute
  '/api/public/bot/debt-payment': typeof ApiPublicBotDebtPaymentRoute
  '/api/public/bot/expense': typeof ApiPublicBotExpenseRoute
  '/api/public/bot/goal-contribution': typeof ApiPublicBotGoalContributionRoute
  '/api/public/bot/income': typeof ApiPublicBotIncomeRoute
  '/api/public/bot/parse': typeof ApiPublicBotParseRoute
  '/api/public/bot/reschedule-task': typeof ApiPublicBotRescheduleTaskRoute
  '/api/public/bot/status-query': typeof ApiPublicBotStatusQueryRoute
  '/api/public/bot/task': typeof ApiPublicBotTaskRoute
  '/api/public/bot/cron/anomaly-alerts': typeof ApiPublicBotCronAnomalyAlertsRoute
  '/api/public/bot/cron/payment-reminders': typeof ApiPublicBotCronPaymentRemindersRoute
  '/api/public/bot/cron/weekly-report': typeof ApiPublicBotCronWeeklyReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/debts'
    | '/expenses'
    | '/goals'
    | '/incomes'
    | '/rating'
    | '/settings'
    | '/tasks'
    | '/api/public/bot/close-task'
    | '/api/public/bot/create-debt'
    | '/api/public/bot/create-goal'
    | '/api/public/bot/debt-payment'
    | '/api/public/bot/expense'
    | '/api/public/bot/goal-contribution'
    | '/api/public/bot/income'
    | '/api/public/bot/parse'
    | '/api/public/bot/reschedule-task'
    | '/api/public/bot/status-query'
    | '/api/public/bot/task'
    | '/api/public/bot/cron/anomaly-alerts'
    | '/api/public/bot/cron/payment-reminders'
    | '/api/public/bot/cron/weekly-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/debts'
    | '/expenses'
    | '/goals'
    | '/incomes'
    | '/rating'
    | '/settings'
    | '/tasks'
    | '/'
    | '/api/public/bot/close-task'
    | '/api/public/bot/create-debt'
    | '/api/public/bot/create-goal'
    | '/api/public/bot/debt-payment'
    | '/api/public/bot/expense'
    | '/api/public/bot/goal-contribution'
    | '/api/public/bot/income'
    | '/api/public/bot/parse'
    | '/api/public/bot/reschedule-task'
    | '/api/public/bot/status-query'
    | '/api/public/bot/task'
    | '/api/public/bot/cron/anomaly-alerts'
    | '/api/public/bot/cron/payment-reminders'
    | '/api/public/bot/cron/weekly-report'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/debts'
    | '/_authenticated/expenses'
    | '/_authenticated/goals'
    | '/_authenticated/incomes'
    | '/_authenticated/rating'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/'
    | '/api/public/bot/close-task'
    | '/api/public/bot/create-debt'
    | '/api/public/bot/create-goal'
    | '/api/public/bot/debt-payment'
    | '/api/public/bot/expense'
    | '/api/public/bot/goal-contribution'
    | '/api/public/bot/income'
    | '/api/public/bot/parse'
    | '/api/public/bot/reschedule-task'
    | '/api/public/bot/status-query'
    | '/api/public/bot/task'
    | '/api/public/bot/cron/anomaly-alerts'
    | '/api/public/bot/cron/payment-reminders'
    | '/api/public/bot/cron/weekly-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicBotCloseTaskRoute: typeof ApiPublicBotCloseTaskRoute
  ApiPublicBotCreateDebtRoute: typeof ApiPublicBotCreateDebtRoute
  ApiPublicBotCreateGoalRoute: typeof ApiPublicBotCreateGoalRoute
  ApiPublicBotDebtPaymentRoute: typeof ApiPublicBotDebtPaymentRoute
  ApiPublicBotExpenseRoute: typeof ApiPublicBotExpenseRoute
  ApiPublicBotGoalContributionRoute: typeof ApiPublicBotGoalContributionRoute
  ApiPublicBotIncomeRoute: typeof ApiPublicBotIncomeRoute
  ApiPublicBotParseRoute: typeof ApiPublicBotParseRoute
  ApiPublicBotRescheduleTaskRoute: typeof ApiPublicBotRescheduleTaskRoute
  ApiPublicBotStatusQueryRoute: typeof ApiPublicBotStatusQueryRoute
  ApiPublicBotTaskRoute: typeof ApiPublicBotTaskRoute
  ApiPublicBotCronAnomalyAlertsRoute: typeof ApiPublicBotCronAnomalyAlertsRoute
  ApiPublicBotCronPaymentRemindersRoute: typeof ApiPublicBotCronPaymentRemindersRoute
  ApiPublicBotCronWeeklyReportRoute: typeof ApiPublicBotCronWeeklyReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rating': {
      id: '/_authenticated/rating'
      path: '/rating'
      fullPath: '/rating'
      preLoaderRoute: typeof AuthenticatedRatingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incomes': {
      id: '/_authenticated/incomes'
      path: '/incomes'
      fullPath: '/incomes'
      preLoaderRoute: typeof AuthenticatedIncomesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/debts': {
      id: '/_authenticated/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof AuthenticatedDebtsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/bot/task': {
      id: '/api/public/bot/task'
      path: '/api/public/bot/task'
      fullPath: '/api/public/bot/task'
      preLoaderRoute: typeof ApiPublicBotTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/status-query': {
      id: '/api/public/bot/status-query'
      path: '/api/public/bot/status-query'
      fullPath: '/api/public/bot/status-query'
      preLoaderRoute: typeof ApiPublicBotStatusQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/reschedule-task': {
      id: '/api/public/bot/reschedule-task'
      path: '/api/public/bot/reschedule-task'
      fullPath: '/api/public/bot/reschedule-task'
      preLoaderRoute: typeof ApiPublicBotRescheduleTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/parse': {
      id: '/api/public/bot/parse'
      path: '/api/public/bot/parse'
      fullPath: '/api/public/bot/parse'
      preLoaderRoute: typeof ApiPublicBotParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/income': {
      id: '/api/public/bot/income'
      path: '/api/public/bot/income'
      fullPath: '/api/public/bot/income'
      preLoaderRoute: typeof ApiPublicBotIncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/goal-contribution': {
      id: '/api/public/bot/goal-contribution'
      path: '/api/public/bot/goal-contribution'
      fullPath: '/api/public/bot/goal-contribution'
      preLoaderRoute: typeof ApiPublicBotGoalContributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/expense': {
      id: '/api/public/bot/expense'
      path: '/api/public/bot/expense'
      fullPath: '/api/public/bot/expense'
      preLoaderRoute: typeof ApiPublicBotExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/debt-payment': {
      id: '/api/public/bot/debt-payment'
      path: '/api/public/bot/debt-payment'
      fullPath: '/api/public/bot/debt-payment'
      preLoaderRoute: typeof ApiPublicBotDebtPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/create-goal': {
      id: '/api/public/bot/create-goal'
      path: '/api/public/bot/create-goal'
      fullPath: '/api/public/bot/create-goal'
      preLoaderRoute: typeof ApiPublicBotCreateGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/create-debt': {
      id: '/api/public/bot/create-debt'
      path: '/api/public/bot/create-debt'
      fullPath: '/api/public/bot/create-debt'
      preLoaderRoute: typeof ApiPublicBotCreateDebtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/close-task': {
      id: '/api/public/bot/close-task'
      path: '/api/public/bot/close-task'
      fullPath: '/api/public/bot/close-task'
      preLoaderRoute: typeof ApiPublicBotCloseTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/cron/weekly-report': {
      id: '/api/public/bot/cron/weekly-report'
      path: '/api/public/bot/cron/weekly-report'
      fullPath: '/api/public/bot/cron/weekly-report'
      preLoaderRoute: typeof ApiPublicBotCronWeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/cron/payment-reminders': {
      id: '/api/public/bot/cron/payment-reminders'
      path: '/api/public/bot/cron/payment-reminders'
      fullPath: '/api/public/bot/cron/payment-reminders'
      preLoaderRoute: typeof ApiPublicBotCronPaymentRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/cron/anomaly-alerts': {
      id: '/api/public/bot/cron/anomaly-alerts'
      path: '/api/public/bot/cron/anomaly-alerts'
      fullPath: '/api/public/bot/cron/anomaly-alerts'
      preLoaderRoute: typeof ApiPublicBotCronAnomalyAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDebtsRoute: typeof AuthenticatedDebtsRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedIncomesRoute: typeof AuthenticatedIncomesRoute
  AuthenticatedRatingRoute: typeof AuthenticatedRatingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDebtsRoute: AuthenticatedDebtsRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedIncomesRoute: AuthenticatedIncomesRoute,
  AuthenticatedRatingRoute: AuthenticatedRatingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicBotCloseTaskRoute: ApiPublicBotCloseTaskRoute,
  ApiPublicBotCreateDebtRoute: ApiPublicBotCreateDebtRoute,
  ApiPublicBotCreateGoalRoute: ApiPublicBotCreateGoalRoute,
  ApiPublicBotDebtPaymentRoute: ApiPublicBotDebtPaymentRoute,
  ApiPublicBotExpenseRoute: ApiPublicBotExpenseRoute,
  ApiPublicBotGoalContributionRoute: ApiPublicBotGoalContributionRoute,
  ApiPublicBotIncomeRoute: ApiPublicBotIncomeRoute,
  ApiPublicBotParseRoute: ApiPublicBotParseRoute,
  ApiPublicBotRescheduleTaskRoute: ApiPublicBotRescheduleTaskRoute,
  ApiPublicBotStatusQueryRoute: ApiPublicBotStatusQueryRoute,
  ApiPublicBotTaskRoute: ApiPublicBotTaskRoute,
  ApiPublicBotCronAnomalyAlertsRoute: ApiPublicBotCronAnomalyAlertsRoute,
  ApiPublicBotCronPaymentRemindersRoute: ApiPublicBotCronPaymentRemindersRoute,
  ApiPublicBotCronWeeklyReportRoute: ApiPublicBotCronWeeklyReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
